# Generated by Django 5.1.7 on 2025-03-13 03:33

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),  # Fixed dependency
    ]

    operations = [
        # Category model
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # City model
        migrations.AddField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Cuisine model
        migrations.AddField(
            model_name='cuisine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuisine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # EventType model
        migrations.AddField(
            model_name='eventtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # PropertyType model
        migrations.AddField(
            model_name='propertytype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertytype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # TransportType model
        migrations.AddField(
            model_name='transporttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transporttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
