# Generated by Django 5.1.7 on 2025-03-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_slug_field_to_attraction"),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='price',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
