# Generated by Django 5.1.7 on 2025-03-13 03:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_price_field_to_attraction"),
    ]

    operations = [
        # Add missing state field to City model with default value "Michigan"
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.CharField(default="Michigan", max_length=50),
        ),
        
        # Add slug field to Restaurant model
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
        
        # Add slug field to Event model
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
        
        # Add slug field to TransportOption model
        migrations.AddField(
            model_name='transportoption',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
        
        # Add featured field to Restaurant model if missing
        migrations.AddField(
            model_name='restaurant',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        
        # Add featured field to Event model if missing
        migrations.AddField(
            model_name='event',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        
        # Add missing timestamp fields to Restaurant
        migrations.AddField(
            model_name='restaurant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Add missing timestamp fields to Event
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Add missing timestamp fields to TransportOption
        migrations.AddField(
            model_name='transportoption',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportoption',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Add missing timestamp fields to Attraction
        migrations.AddField(
            model_name='attraction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attraction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
