# Generated by Django 5.1.7 on 2025-03-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_align_schema_with_models"),
    ]

    operations = [
        # Add rating field to Attraction
        migrations.AddField(
            model_name='attraction',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        # Add review_count field to Attraction
        migrations.AddField(
            model_name='attraction',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
