# Generated by Django 5.1.7 on 2025-03-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_add_rating_fields_to_attraction"),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='price_level',
            field=models.IntegerField(default=1),
        ),
    ]
