# Generated by Django 5.1.7 on 2025-03-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_add_rating_to_restaurant"),
    ]

    operations = [
        # Add the missing address field
        migrations.AddField(
            model_name='transportoption',
            name='address',
            field=models.CharField(blank=True, max_length=255, default=''),
            preserve_default=False,
        ),
        # Add the missing featured field
        migrations.AddField(
            model_name='transportoption',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        # Add the missing slug field
        migrations.AddField(
            model_name='transportoption',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True, default=''),
            preserve_default=False,
        ),
    ]
